#+title: Bonk's emacs config
#+OPTIONS: toc:t
#+PROPERTY: header-args:emacs-lisp :tangle ./init.el :mkdirp yes

* Basic UI config
** General conf
#+begin_src emacs-lisp

	(setq inhibit-startup-message t)
  (setq warning-minimum-level :emergency)

	(scroll-bar-mode -1) ; Disable visible scrollbar
	(tool-bar-mode -1)   ; Disable the toolbar
	(tooltip-mode -1)    ; Disable tooltips
	(set-fringe-mode 10) ; Give some breathing room

	(menu-bar-mode -1)   ; isable the menu bar

	;; Set up the visible bell
	(setq visible-bell t)

  (column-number-mode)
  (global-display-line-numbers-mode t)

  ;; Disable line numbers for some modes
  (dolist (mode '(org-mode-hook
				  term-mode-hook
				  shell-mode-hook
				  eshell-mode-hook))
	(add-hook mode (lambda () (display-line-numbers-mode 0))))

#+end_src

** Font Configuration

#+begin_src emacs-lisp

  (set-face-attribute 'default nil :font  "Sarasa Gothic CL-12")
  (set-face-font 'variable-pitch "Iosevka-12")
  (set-face-font 'fixed-pitch "Sarasa Gothic CL-12")

  ;;============================================================
  ;; toggle between variable pitch and fixed pitch font for 
  ;; the current buffer
  (defun fixed-pitch-mode ()
	(buffer-face-mode -1))

  (defun variable-pitch-mode ()
	(buffer-face-mode t))

  (defun toggle-pitch (&optional arg)
	"Switch between the `fixed-pitch' face and the `variable-pitch' face"
	(interactive)
	(buffer-face-toggle 'variable-pitch))

  ;; enable buffer-face mode to provide buffer-local fonts
  (buffer-face-mode)

  ;; Set the fonts to format correctly
  (add-hook 'text-mode-hook 'fixed-pitch-mode)
  (add-hook 'dired-mode-hook 'variable-pitch-mode)
  (add-hook 'calendar-mode-hook 'variable-pitch-mode)
  (add-hook 'org-agenda-mode-hook 'variable-pitch-mode)
  (add-hook 'shell-mode-hook 'variable-pitch-mode)
  (add-hook 'eshell-mode-hook 'variable-pitch-mode)
  (add-hook 'neotree-mode-hook 'variable-pitch-mode)
  (add-hook 'counsel-mode-hook 'variable-pitch-mode)
  (add-hook 'command-log-mode-hook 'variable-pitch-mode)
  (add-hook 'which-key-mode-hook 'variable-pitch-mode)
  (add-hook 'ivy-mode-hook 'variable-pitch-mode)
  (add-hook 'helpful-mode-hook 'variable-pitch-mode)
										  ;(Add-hook 'bs-mode-hook 'fixed-pitch-mode)
										  ;(add-hook 'w3m-mode-hook 'variable-pitch-mode)
										  ;(add-hook 'org-mode-hook 'variable-pitch-mode)
  (add-hook 'eww-mode-hook 'variable-pitch-mode)

  ;; (C-q Tab) inserts a tab space
  (add-hook 'ess-mode-hook (lambda () (local-set-key "\t" 'self-insert-command)))


#+end_src

* Package And System setup

#+begin_src emacs-lisp
  ;; Initialize package sources
  (require 'package)

  (setq package-archives '(("melpa" . "https://melpa.org/packages/")
			   ("org" . "https://orgmode.org/elpa/")
			   ("elpa" . "https://elpa.gnu.org/packages/")))


  (setq package-check-signature nil) 
  ;; probably not necessary


  (package-initialize)
  (unless package-archive-contents
    (package-refresh-contents))
  (use-package exec-path-from-shell)
  (when (memq window-system '(mac ns x))
    (exec-path-from-shell-initialize))

  ;; Initialize use-package on non-Linux platforms
  (unless (package-installed-p 'use-package)
    (package-install 'use-package))

  (require 'use-package)
  (setq use-package-always-ensure t)
  (use-package use-package-ensure-system-package)

#+end_src

#+RESULTS:

* Keybinding Configuration

This configuration uses [[https://evil.readthedocs.io/en/latest/index.html][evil-mode]] for a Vi-like modal editing experience.
[[https://github.com/noctuid/general.el][general.el]] is used for easy keybinding configuration that integrates well with which-key.
[[https://github.com/emacs-evil/evil-collection][evil-collection]] is used to automatically configure various Emacs modes with Vi-like keybindings
for evil-mode.

#+begin_src emacs-lisp

  ;; Make ESC quit prompts
  (global-set-key (kbd "<escape>") 'keyboard-escape-quit)

  (use-package general
	:config
	(general-create-definer bonk/leader-keys
	  :keymaps '(normal insert visual emacs)
	  :prefix "SPC"
	  :global-prefix "C-SPC"))

	(bonk/leader-keys
	  "t"  '(:ignore t :which-key "toggles")
	  "tt" '(counsel-load-theme :which-key "choose theme")
	;; Window navigation
	  "H" '(windmove-left :which-key "move to left window")
	  "L" '(windmove-right :which-key "move to right window")
	  "J" '(windmove-down :which-key "move to below window")
	  "K" '(windmove-up :which-key "move to above window")
	;; Buffer options
	  "DD" '(kill-this-buffer :which "kills the current buffer")
	  "vcc" '(vterm-send-C-c :which "kills current vterm process")
	  "nn" '(neotree-toggle :which "toggles neotree")
	  )

  (use-package evil
	:init
	(setq evil-want-integration t)
	(setq evil-want-keybinding nil)
	(setq evil-want-C-u-scroll t)
	(setq evil-want-C-i-jump nil)
	:config
	(evil-mode 1)
	(define-key evil-insert-state-map (kbd "C-g") 'evil-normal-state)
	(define-key evil-insert-state-map (kbd "C-h") 'evil-delete-backward-char-and-join)

	;; Use visual line motions even outside of visual-line-mode buffers
	(evil-global-set-key 'motion "j" 'evil-next-visual-line)
	(evil-global-set-key 'motion "k" 'evil-previous-visual-line)

	(evil-set-initial-state 'messages-buffer-mode 'normal)
	(evil-set-initial-state 'dashboard-mode 'normal))

  (use-package evil-collection
	:after evil
	:config
	(evil-collection-init))

#+end_src

* UI Configuration

** Command Log Mode

[[https://github.com/lewang/command-log-mode][command-log-mode]] is useful for displaying a panel showing each key binding you use in a panel on the right side of the frame.  Great for live streams and screencasts!

#+begin_src emacs-lisp

	  (use-package command-log-mode
		:commands command-log-mode)

#+end_src

#+RESULTS:

** Color Theme

[[https://github.com/hlissner/emacs-doom-themes][doom-themes]] is a great set of themes with a lot of variety and support for many different Emacs modes.  Taking a look at the [[https://github.com/hlissner/emacs-doom-themes/tree/screenshots][screenshots]] might help you decide which one you like best.  You can also run =M-x counsel-load-theme= to choose between them easily.

#+begin_src emacs-lisp

  (use-package doom-themes
  :init (load-theme 'doom-zenburn t))
  (use-package ewal-spacemacs-themes)
  (use-package moe-theme)
  (use-package zenburn-theme)
  (use-package yoshi-theme)
  (use-package sublime-themes)
  (use-package gruvbox-theme)
  (use-package color-theme-sanityinc-tomorrow)
  (use-package cyberpunk-theme)

#+end_src

#+RESULTS:

** Better Modeline

[[https://github.com/seagle0128/doom-modeline][doom-modeline]] is a very attractive and rich (yet still minimal) mode line configuration for Emacs.  The default configuration is quite good but you can check out the [[https://github.com/seagle0128/doom-modeline#customize][configuration options]] for more things you can enable or disable.

*NOTE:* The first time you load your configuration on a new machine, you'll need to run `M-x all-the-icons-install-fonts` so that mode line icons display correctly.

#+begin_src emacs-lisp

(use-package all-the-icons)

(use-package doom-modeline
  :init (doom-modeline-mode 1)
  :custom ((doom-modeline-height 15)))

#+end_src

#+RESULTS:

** Which Key

[[https://github.com/justbur/emacs-which-key][which-key]] is a useful UI panel that appears when you start pressing any key binding in Emacs to offer you all possible completions for the prefix.  For example, if you press =C-c= (hold control and press the letter =c=), a panel will appear at the bottom of the frame displaying all of the bindings under that prefix and which command they run.  This is very useful for learning the possible key bindings in the mode of your current buffer.

#+begin_src emacs-lisp

  (use-package which-key
	:defer 0
	:diminish which-key-mode
	:config
	(which-key-mode)
	(set-face-attribute 'which-key-local-map-description-face nil :font "Iosevka-12")
	(set-face-attribute 'which-key-key-face nil :font "Iosevka-12")
	(set-face-attribute 'which-key-separator-face nil :font "Iosevka-12")
	(set-face-attribute 'which-key-note-face nil :font "Iosevka-12")
	(set-face-attribute 'which-key-special-key-face nil :font "Iosevka-12")
	(set-face-attribute 'which-key-group-description-face nil :font "Iosevka-12")
	(set-face-attribute 'which-key-command-description-face nil :font "Iosevka-12")
	(setq which-key-idle-delay 1)
	(setq which-key-allow-imprecise-window-fit t))


#+end_src

#+RESULTS:
: t

** Ivy and Counsel

[[https://oremacs.com/swiper/][Ivy]] is an excellent completion framework for Emacs.  It provides a minimal yet powerful selection menu that appears when you open files, switch buffers, and for many other tasks in Emacs.  Counsel is a customized set of commands to replace `find-file` with `counsel-find-file`, etc which provide useful commands for each of the default completion commands.

[[https://github.com/Yevgnen/ivy-rich][ivy-rich]] adds extra columns to a few of the Counsel commands to provide more information about each item.

#+begin_src emacs-lisp

    (use-package ivy
      :diminish
      :bind (("C-s" . swiper)
             :map ivy-minibuffer-map
             ("TAB" . ivy-alt-done)
             ("C-l" . ivy-alt-done)
             ("C-j" . ivy-next-line)
             ("C-k" . ivy-previous-line)
             :map ivy-switch-buffer-map
             ("C-k" . ivy-previous-line)
             ("C-l" . ivy-done)
             ("C-d" . ivy-switch-buffer-kill)
             :map ivy-reverse-i-search-map
             ("C-k" . ivy-previous-line)
             ("C-d" . ivy-reverse-i-search-kill))
      :config
      (ivy-mode 1))

    (use-package ivy-rich
      :init
      (ivy-rich-mode 1))

    (use-package counsel
      :bind (("C-M-j" . 'counsel-switch-buffer)
             :map minibuffer-local-map
             ("C-r" . 'counsel-minibuffer-history))
      :config
      (counsel-mode 1))

#+end_src

#+RESULTS:
: counsel-minibuffer-history

** Helpful Help Commands

[[https://github.com/Wilfred/helpful][Helpful]] adds a lot of very helpful (get it?) information to Emacs' =describe-= command buffers.  For example, if you use =describe-function=, you will not only get the documentation about the function, you will also see the source code of the function and where it gets used in other places in the Emacs configuration.  It is very useful for figuring out how things work in Emacs.

#+begin_src emacs-lisp

  (use-package helpful
	:commands (helpful-callable helpful-variable helpful-command helpful-key)
	:custom
	(counsel-describe-function-function #'helpful-callable)
	(counsel-describe-variable-function #'helpful-variable)
	:bind
	([remap describe-function] . counsel-describe-function)
	([remap describe-command] . helpful-command)
	([remap describe-variable] . counsel-describe-variable)
	([remap describe-key] . helpful-key))

#+end_src

#+RESULTS:
: helpful-key

** Text Scaling

This is an example of using [[https://github.com/abo-abo/hydra][Hydra]] to design a transient key binding for quickly adjusting the scale of the text on screen.  We define a hydra that is bound to =C-s t s= and, once activated, =j= and =k= increase and decrease the text scale.  You can press any other key (or =f= specifically) to exit the transient key map.

#+begin_src emacs-lisp

	  (use-package hydra
		:defer t)

	  (defhydra hydra-text-scale (:timeout 4)
		"scale text"
		("j" text-scale-increase "in")
		("k" text-scale-decrease "out")
		("f" nil "finished" :exit t))

	  (bonk/leader-keys
		"ts" '(hydra-text-scale/body :which-key "scale text"))

#+end_src

#+RESULTS:

** Rule mode
   #+begin_src emacs-lisp
     ;; Use ruler in text-mode
 ;;    (add-hook 'text-mode-hook
	;;       (function (lambda ()
		;;	   (setq ruler-mode-show-tab-stops t)
			;;   (ruler-mode 1))))
   #+end_src

   #+RESULTS:

** Ido (tool for buffer)
   #+begin_src emacs-lisp
	 (use-package ido
	   :config
	   (ido-mode 'buffers) ;; only use this line to turn off ido for file names!
	   (setq ido-ignore-buffers '("^ " "*Completions*" "*Shell Command Output*"
								  "*Messages*" "Async Shell Command")))
   #+end_src

   #+RESULTS:

* Org Mode

** Basic configuration

#+begin_src emacs-lisp

  (defun bonk/org-no-line-number ()
	(global-display-line-numbers-mode 0))

	(use-package org
	  :pin org
	  :commands (org-capture org-agenda)
	  :hook
	  (org-mode . bonk/org-mode-setup)
	   (org-mode . bonk/org-no-line-number)
	  :config
	  (setq org-ellipsis " ▾")
	  (bonk/org-font-setup))


#+end_src

** Better Font Faces

#+begin_src emacs-lisp

    (defun bonk/org-font-setup ()
      ;; Replace list hyphen with dot
      (font-lock-add-keywords 'org-mode
			      '(("^ *\\([-]\\) "
				 (0 (prog1 () (compose-region (match-beginning 1) (match-end 1) "•"))))))

      ;; Set faces for heading levels
      (dolist (face '((org-level-1 . 1.2)
		      (org-level-2 . 1.1)
		      (org-level-3 . 1.05)
		      (org-level-4 . 1.0)
		      (org-level-5 . 1.1)
		      (org-level-6 . 1.1)
		      (org-level-7 . 1.1)
		      (org-level-8 . 1.1)))
	(set-face-attribute (car face) nil :font "Sarasa Fixed Slab K"
			    :weight 'regular
			    :height (cdr face)))

      ;; Ensure that anything that should be fixed-pitch in Org files appears that way
      (set-face-attribute 'org-block nil :foreground nil :inherit 'fixed-pitch)
      (set-face-attribute 'org-code nil   :inherit '(shadow fixed-pitch))
      (set-face-attribute 'org-table nil   :inherit '(shadow fixed-pitch))
      (set-face-attribute 'org-verbatim nil :inherit '(shadow fixed-pitch))
      (set-face-attribute 'org-special-keyword nil :inherit '(font-lock-comment-face fixed-pitch))
      (set-face-attribute 'org-meta-line nil :inherit '(font-lock-comment-face fixed-pitch))
      (set-face-attribute 'org-checkbox nil :inherit 'fixed-pitch))


#+end_src

** Nicer Heading Bullets
#+begin_src emacs-lisp
(use-package org-bullets
  :after org
  :hook (org-mode . org-bullets-mode)
  :custom
  (org-bullets-bullet-list '("◉" "○" "●" "○" "●" "○" "●")))

#+end_src

** Center Org Buffers
   
#+begin_src emacs-lisp
  (defun bonk/org-mode-visual-fill ()
	(setq visual-fill-column-width 100
		  visual-fill-column-center-text t)
	(visual-fill-column-mode 1))

  (use-package visual-fill-column
	:after org
	:hook (org-mode . bonk/org-mode-visual-fill))


#+end_src

** Auto-tangle Configuration FIles

#+begin_src emacs-lisp
  ;; Automatically tangle our Emacs.org config file when we save it
  (defun bonk/org-babel-tangle-config ()
    (when (string-equal (buffer-file-name)
                        (expand-file-name "~/github/emacs-config/config.org"))
      ;; Dynamic scoping to the rescue
      (let ((org-confirm-babel-evaluate nil))
        (org-babel-tangle)))
    (add-hook 'org-mode-hook (lambda () (add-hook 'after-save-hook #'bonk/org-babel-tangle-config))))

#+end_src

** Configure Babel Languages

To execute or export code in =org-mode= code blocks, you'll need to set up =org-babel-load-languages= for each language you'd like to use.  [[https://orgmode.org/worg/org-contrib/babel/languages.html][This page]] documents all of the languages that you can use with =org-babel=.

#+begin_src emacs-lisp
	  (with-eval-after-load 'org
		(org-babel-do-load-languages
		  'org-babel-load-languages
		  '((emacs-lisp . t)
			(python . t)
			(typescript . t)
			(go . t)
			(rust . t)))

		(push '("conf-unix" . conf-unix) org-src-lang-modes))
#+end_src

* Development
** General configs

   Here is the config for wether using tabs, how to indent, how many spaces, etc.

   #+begin_src emacs-lisp

	 (setq-default indent-tabs-mode t)
	 (setq-default tab-width 4) ; I want tabs to be four spaces wide
	 ;; Indentation levels for each lang
	 (defvaralias 'js2-basic-offset 'tabwidth)
	 (defvaralias 'js-indent-level 'tab-width)
	 (defvaralias 'js-indent-level 'tab-width)
	 (defvaralias 'rjsx-indent-level 'tab-width)
	 (defvaralias 'rjsx-mode-markup-indent-offset 'tab-width)
	 (defvaralias 'rjsx-mode-code-indent-offset 'tab-width)
	 (defvaralias 'web-mode-css-indent-offset 'tab-width)
	 (defvaralias 'js2-indent-level 'tab-width)

	 ;; Increase for better lsp-mode performance; see
	 ;; https://emacs-lsp.github.io/lsp-mode/page/performance/
	 (setq gc-cons-threshold 100000000)
	 (when (boundp 'read-process-output-max)
	   ;; New in Emacs 27
	   (setq read-process-output-max (* 2048 2048)))
   #+end_src
** Languages

*** IDE Features with lsp-mode

**** lsp-mode

We use the excellent [[https://emacs-lsp.github.io/lsp-mode/][lsp-mode]] to enable IDE-like functionality for many different programming languages via "language servers" that speak the [[https://microsoft.github.io/language-server-protocol/][Language Server Protocol]].  Before trying to set up =lsp-mode= for a particular language, check out the [[https://emacs-lsp.github.io/lsp-mode/page/languages/][documentation for your language]] so that you can learn which language servers are available and how to install them.

The =lsp-keymap-prefix= setting enables you to define a prefix for where =lsp-mode='s default keybindings will be added.  I *highly recommend* using the prefix to find out what you can do with =lsp-mode= in a buffer.

The =which-key= integration adds helpful descriptions of the various keys so you should be able to learn a lot just by pressing =C-c l= in a =lsp-mode= buffer and trying different things that you find there.

#+begin_src emacs-lisp


	(defun bonk/lsp-mode-setup ()
	  (setq lsp-headerline-breadcrumb-segments '(path-up-to-project file symbols))
	  (lsp-headerline-breadcrumb-mode))

	(use-package lsp-mode
	  :ensure t
	  :commands (lsp lsp-deferred)
	  :hook (lsp-mode . bonk/lsp-mode-setup)
	  :init
	  (setq lsp-keymap-prefix "C-c l")  ;; Or 'C-l', 's-l'
	  :config

	  (add-hook 'typescript-mode-hook 'lsp)
	  (add-hook 'rjsx-mode-hook 'lsp)
	  (add-hook 'php-mode 'lsp)
	  (add-hook 'css-mode 'lsp)
	  (add-hook 'web-mode 'lsp)
	  (lsp-enable-which-key-integration t)
	  (setq lsp-completion-enable t)

	  (setq lsp-language-id-configuration '((java-mode . "java")
						(python-mode . "python")
						(gfm-view-mode . "markdown")
						(rust-mode . "rust")
						(css-mode . "css")
						(xml-mode . "xml")
						(c-mode . "c")
						(c++-mode . "cpp")
						(objc-mode . "objective-c")
						(web-mode . "html")
						(html-mode . "html")
						(sgml-mode . "html")
						(mhtml-mode . "html")
						(go-mode . "go")
						(haskell-mode . "haskell")
						(php-mode . "php")
						(json-mode . "json")
						(rjsx-mode . "javascript")
						(typescript-mode . "typescript")
						))

	  (setq lsp-diagnostics-provider :none)

	  :custom
	  (lsp-file-watch-threshold nil)
	  (lsp-solargraph-multi-root nil))

#+end_src

**** lsp-ui

[[https://emacs-lsp.github.io/lsp-ui/][lsp-ui]] is a set of UI enhancements built on top of =lsp-mode= which make Emacs feel even more
like an IDE.  Check out the screenshots on the =lsp-ui= homepage (linked at the beginning
of this paragraph) to see examples of what it can do.

#+begin_src emacs-lisp

  (use-package lsp-ui
    :hook (lsp-mode . lsp-ui-mode)
    :custom
    (lsp-ui-doc-position 'bottom))

#+end_src

**** lsp-treemacs

[[https://github.com/emacs-lsp/lsp-treemacs][lsp-treemacs]] provides nice tree views for different aspects of your code like symbols in a file, references of a symbol, or diagnostic messages (errors and warnings) that are found in your code.

Try these commands with =M-x=:

- =lsp-treemacs-symbols= - Show a tree view of the symbols in the current file
- =lsp-treemacs-references= - Show a tree view for the references of the symbol under the cursor
- =lsp-treemacs-error-list= - Show a tree view for the diagnostic messages in the project

This package is built on the [[https://github.com/Alexander-Miller/treemacs][treemacs]] package which might be of some interest to you if you like to have a file browser at the left side of your screen in your editor.

#+begin_src emacs-lisp

  (use-package lsp-treemacs
    :after lsp)

#+end_src

**** lsp-ivy

[[https://github.com/emacs-lsp/lsp-ivy][lsp-ivy]] integrates Ivy with =lsp-mode= to make it easy to search for things by name in your code.  When you run these commands, a prompt will appear in the minibuffer allowing you to type part of the name of a symbol in your code.  Results will be populated in the minibuffer so that you can find what you're looking for and jump to that location in the code upon selecting the result.

Try these commands with =M-x=:

- =lsp-ivy-workspace-symbol= - Search for a symbol name in the current project workspace
- =lsp-ivy-global-workspace-symbol= - Search for a symbol name in all active project workspaces

#+begin_src emacs-lisp

	(use-package lsp-ivy
	  :after lsp)

#+end_src

**** lsp-clients
     #+begin_src emacs-lisp
     #+end_src
*** Yasnippets
    Yasnippet automatically inserts code templates when I write a word and press the tab key.
    It predefines most of the common templates, including the dreadful =if err !\=nil { ....=

    #+begin_src emacs-lisp

	  (use-package yasnippet                  ; Snippets
		:after company
		:config
		(setq
		 yas-verbosity 1                      ; No need to be so verbose
		 yas-wrap-around-region t)

		(with-eval-after-load 'yasnippet
		  (setq yas-snippt-dirs '(yasnippet-snippets-dir)))

		(yas-reload-all)
		(yas-global-mode))

	  (use-package yasnippet-snippets         ; Collection of snippets
		:after yasnippet)
    #+end_src

*** Flycheck

    Flycheck is one of the two main packages for code checks in the background. The
    other one is Flymake. I use Flycheck because it allows me to define a custom “advanced”
    checker.
    #+begin_src emacs-lisp

			(use-package flycheck
			  :after company)
			(setq flycheck-disabled-checkers '(ruby ruby-reek ruby-rubocop ruby-rubylint yaml-ruby))

    #+end_src
*** TypeScript

This is a basic configuration for the TypeScript language so that =.ts= files activate =typescript-mode= when opened.  We're also adding a hook to =typescript-mode-hook= to call =lsp-deferred= so that we activate =lsp-mode= to get LSP features every time we edit TypeScript code.

#+begin_src emacs-lisp

  (use-package typescript-mode
    :mode "\\.ts\\'"
    :hook (typescript-mode . lsp-deferred))

#+end_src

*Important note!*  For =lsp-mode= to work with TypeScript (and JavaScript) you will need to install a language server on your machine.  If you have Node.js installed, the easiest way to do that is by running the following command:

#+begin_src shell :tangle no

npm install -g typescript-language-server typescript

#+end_src

This will install the [[https://github.com/theia-ide/typescript-language-server][typescript-language-server]] and the TypeScript compiler package.

*** Ruby
**** inf-ruby
     #+begin_src emacs-lisp
			  (use-package inf-ruby
				:after lsp)
     #+end_src
     
**** ruby-mode
     #+begin_src emacs-lisp
	   (use-package ruby-mode
		 :mode "\\.rb\\'"
		 :hook ((ruby-mode . lsp-deferred))
		 :config
		 (setq ruby-indent-tabs-mode t)
		 (setq ruby-indent-level tab-width))

	   (use-package enh-ruby-mode
		 :after ruby-mode
		 :config
		 (setq enh-ruby-indent-tabs-mode t))

     #+end_src

**** robe-mode
     #+begin_src emacs-lisp
					 (use-package robe
					   :after ruby-mode)
					 (add-hook 'ruby-mode-hook 'robe-mode)
					 (eval-after-load 'company
					   '(push 'company-robe company-backends))
     #+end_src
     
**** Flymake
     #+begin_src emacs-lisp
		 (require 'flymake-ruby)
		 (add-hook 'ruby-mode-hook 'flymake-ruby-load)
     #+end_src

**** rspec-mode
     #+begin_src emacs-lisp
	   (use-package rspec-mode
		 :after ruby-mode)
	   (eval-after-load 'rspec-mode
		 '(rspec-install-snippets))
     #+end_src
*** Golang
    
    #+begin_src emacs-lisp
	  (use-package go-mode
		:mode "\\.go\\'"
		:hook (go-mode . lsp-deferred)
		:config
		(add-hook 'go-mode-hook (lambda ()
								  (setq tab-width 4)))
		(add-hook 'go-mode-hook #'lsp)
		(add-hook 'before-save-hook 'gofmt-before-save)
		(defun lsp-go-install-save-hooks ()
		  (add-hook 'before-save-hook 'lsp-format-buffer t t)
		  (add-hook 'before-save-hook 'lsp-organize-imports t t))
		(add-hook 'go-mode-hook 'lsp-go-install-save-hooks)
		;; configure gopls
		(lsp-register-custom-settings
		 '(("gopls.completeUnimported" t t)
		   ("gopls.staticcheck" t t)))
		;; Start LSP Mode and YASnippet mode
		(add-hook 'go-mode-hook 'lsp-deferred)
		(add-hook 'go-mode-hook 'yas-minor-mode))

    #+end_src
    
*** Elisp
*** Rust
*** C/C++
*** Javascript
***** Web Mode
#+begin_src emacs-lisp

  (use-package web-mode
	:mode "\\.html$'" "\\.jsx$" "\\.tsx$"
	:init 
	(setq web-mode-markup-indent-offset 4)
	(setq web-mode-css-indent-offset 4)
	(setq web-mode-code-indent-offset 4)
	)

#+end_src
***** RJSX mode
      It has all the features from js2 , and all the js files i've been using till now are .js
      files, so i don't really need to differentiate between modes
    #+begin_src emacs-lisp
	  (use-package rjsx-mode
		:mode "\\.js\\'"
		:hook (rjsx-mode . lsp-deferred)
		:init
		(setq indent-tabs-mode t)
		(setq js2-basic-offset 4))

	#+end_src

***** Tide
      #+begin_src emacs-lisp
	(defun setup-tide-mode()
	  "Setup function for tide."
	  (interactive)
	  (tide-setup)
	  (flycheck-mode +1)
	  (setq flycheck-check-syntax-automatically '(save mode-enabled)))

	  (use-package tide
	    :after (rjsx-mode company flycheck)
	    :hook (rjsx-mode . setup-tide-mode))

      #+end_src

***** Prettier 

  It is important to have prettier installed through npm beforehand though
  =npm install -g prettier=
    #+begin_src emacs-lisp
	  (use-package prettier-js
		:after (rjsx-mode)
		:hook (rjsx-mode . setup-tide-mode))

    #+end_src
	
*** Yaml
    #+begin_src emacs-lisp
	  ;; yaml-mode doesn't derive from prog-mode, but we can at least enable
	  ;; whitespace-mode and apply cleanup.
	  (use-package yaml-mode
		:after lsp-mode
		:config
		(add-hook 'yaml-mode-hook 'whitespace-mode)
		(add-hook 'yaml-mode-hook 'subword-mode))

    #+end_src
    
** Company Mode

[[http://company-mode.github.io/][Company Mode]] provides a nicer in-buffer completion interface than =completion-at-point= which is more reminiscent of what you would expect from an IDE.  We add a simple configuration to make the keybindings a little more useful (=TAB= now completes the selection and initiates completion at the current location if needed).

We also use [[https://github.com/sebastiencs/company-box][company-box]] to further enhance the look of the completions with icons and better overall presentation.

#+begin_src emacs-lisp

  (use-package company
    :after lsp-mode
    :hook (lsp-mode . company-mode)
    :bind (:map company-active-map
		("<tab>" . company-complete-selection))
    (:map lsp-mode-map
	  ("<tab>" . company-indent-or-complete-common))
    :custom
    (company-minimum-prefix-length 1)
    (company-idle-delay 0.2))

  (global-company-mode t)
  (use-package company-box
    :hook (company-mode . company-box-mode))
  (eval-after-load 'company
    '(push 'company-robe company-backends))

#+end_src
*** Company Backends
**** Golang
   #+begin_src emacs-lisp

     #+end_src

**** Ruby
     #+begin_src emacs-lisp
       (use-package company-inf-ruby
	 :after (company ruby-mode)
	 :config (add-to-list 'company-backends 'company-inf-ruby))
     #+end_src

**** JavaScript
     #+begin_src emacs-lisp

       (use-package ac-js2
	 :after (company tide js2-mode web-mode)
	 :config (add-to-list 'company-backends 'ac-js2))

     #+end_src

**** Web
     #+begin_src emacs-lisp

	;; HTML company backend
       (use-package company-web
	 :after (company web-mode)
	 :config (add-to-list 'company-backends 'company-web))
;; WIP missing CSS backend
     #+end_src

**** eLisp
     #+begin_src emacs-lisp
	   ;; Add `company-elisp' backend for elisp.
	   (add-hook 'emacs-lisp-mode-hook
				 '(lambda ()
					(require 'company-elisp)
					(push 'company-elisp company-backends)))

     #+end_src
     
** Projectile

[[https://projectile.mx/][Projectile]] is a project management library for Emacs which makes it a lot easier to navigate around code projects for various languages.  Many packages integrate with Projectile so it's a good idea to have it installed even if you don't use its commands directly.

#+begin_src emacs-lisp

  (use-package projectile
    :diminish projectile-mode
    :config (projectile-mode)
    :custom ((projectile-completion-system 'ivy))
    :bind-keymap
    ("C-c p" . projectile-command-map)
    :init
    ;; NOTE: Set this to the folder where you keep your Git repos!
    (when (file-directory-p "~/github")
      (setq projectile-project-search-path '("~/github")))
    (setq projectile-switch-project-action #'projectile-dired))

  (use-package counsel-projectile
    :config (counsel-projectile-mode))

#+end_src

** Magit

[[https://magit.vc/][Magit]] is the best Git interface I've ever used.  Common Git operations are easy to execute quickly using Magit's command panel system.

#+begin_src emacs-lisp

  (use-package magit
    :custom
    (magit-display-buffer-function #'magit-display-buffer-same-window-except-diff-v1))

  ;; NOTE: Make sure to configure a GitHub token before using this package!
  ;; - https://magit.vc/manual/forge/Token-Creation.html#Token-Creation
  ;; - https://magit.vc/manual/ghub/Getting-Started.html#Getting-Started
  ;; (use-package forge)

#+end_src

** Rainbow Delimiters

[[https://github.com/Fanael/rainbow-delimiters][rainbow-delimiters]] is useful in programming modes because it colorizes nested parentheses and brackets according to their nesting depth.  This makes it a lot easier to visually match parentheses in Emacs Lisp code without having to count them yourself.

#+begin_src emacs-lisp

(use-package rainbow-delimiters
  :hook (prog-mode . rainbow-delimiters-mode))

#+end_src

* Terminals
** Term-mode
   =term-mode= is a built-in terminal emulator in Emacs. Because it is written in Emacs Lisp, you
   can start using it inmediately with very little configuration. If you are on Linux or macOs,
   =term-mode= is a great choice to get started because it supports fairly complex terminal applications
   (=htop=, =vim= , etc) and works pretty reliably.

   However, because it is written in ELisp, it can be slower than the other options like =vterm=.
   The speed will only be an issue if you regularly run console apps with a lot of output.

   - *line-mode*: It enables you to use normal Emacs keybindings while moving around in the terminal
     buffer ( it's similar to NORMAL mode in vim)
   - *char-mode*: It's similar to insert mode in VIM, meaning that , it allows you to write in
     the terminal buffer.

   With =evil-collection= installed, you will automatically switch to =char-mode= whenever you
   enter insert mode, and when escaping, you will return to =line-mode=.

   You can try running a terminal with =M-x term!=. :)

*** Useful key bindings:
    - =C-c C-p= / =C-c C-n= - go back and forward in the buffer's promts( also =[[= and =]\]= with
      evil-mode)
    - =C-c C-k= - Enter char-mode
    - =C-c C-j= - Return to line-mode
    - If you have =evil-collection= term-mode will work the way i mentioned before.

    #+begin_src emacs-lisp
	  (use-package term
		:commands term
		:config
		(setq explicit-shell-file-name "zsh") ;; You can change this to bash, fish, etc
		;;(setq explicit-zsh-args '()) ;; Use it to set especific shell args
		(setq term-prompt-regexp "^[^#$%>\n]*[#$%>] *"))

   #+end_src

*** Term-mode 256color
    The =eterm-256color= package enhances the output of =term-mode= to enable handling of a
    wider range of color codes so that many popular terminal applications look as you would
    expect them to.  Keep in mind that this package requires =ncurses= to be installed on your
    machine so that it has access to the =tic= program.  Most Linux distributions come with
    this program installed already so you may not have to do anything extra to use it.

#+begin_src emacs-lisp

  (use-package eterm-256color
	:after term
	:hook (term-mode . eterm-256color-mode))

#+end_src

** Vterm
   [[https://github.com/akermu/emacs-libvterm/][vterm]] is an improved terminal emulator package which uses a compiled native module to
   interact with the underlying terminal applications. This enables it to be much faster
   than =term-mode= and to also provide a more complete terminal emulation experience.
   Make sure that you have the [[https://github.com/akermu/emacs-libvterm/#requirements][necessary dependencies]] installed before trying to use
   =vterm= because there is a module that will need to be compiled before you can use it
   successfully.

#+begin_src emacs-lisp

  (use-package vterm
    :commands vterm
    :hook (vterm-mode . hide-mode-line-mode) ; modeline serves no purpose in vterm
    :config
    (setq vterm-shell "zsh")                       ;; Set this to customize the shell to launch
    (setq vterm-max-scrollback 10000)
    ;; Once vterm is dead, the vterm buffer is useless. Why keep it around? We can
    ;; spawn another if want one.
    (setq vterm-kill-buffer-on-exit t)
    (setq vterm-timer-delay 0.01))

#+end_src

*** Keybindings for opening vterm in other windows with =SPACE v +options=

#+begin_src emacs-lisp
	(bonk/leader-keys
	  "vt" '(vterm-other-window :which-key "vterm in new window")
	  "vb" '(vterm :which-key "open new buffer for vterm"))

#+end_src

** Shell-mode
   TBD (i'm pretty satisfied with vterm, but i could try this one day)
** Eshell
   TBD (i'm pretty satisfied with vterm, but i could try this one day)
* File Management
** Backup-files
*** Configuration

I don't like when emacs creates backup files next to the originals, since it can be tedious
to commit changes on a project.

#+begin_src emacs-lisp
;; Backup and Autosave Directories
  (setq temporary-file-directory "~/.tmp/emacs/")
  (setq auto-save-file-name-transforms
	`((".*" ,temporary-file-directory t)))
  (setq backup-directory-alist            '((".*" . "~/.Trash")))
#+end_src

** Dired
*** Key Bindings

**** Navigation
**** Emacs / Evil
- =n= / =j= - next line
- =p= / =k= - previous line
- =j= / =J= - jump to file in buffer
- =RET= - select file or directory
- =^= - go to parent directory
- =S-RET= / =g O= - Open file in "other" window
- =M-RET= - Show file in other window without focusing (previewing files)
- =g o= (=dired-view-file=) - Open file but in a "preview" mode, close with =q=
- =g= / =g r= Refresh the buffer with =revert-buffer=
  after changing configuration (and after filesystem changes!)

**** Marking Files
- =m= - Marks a file
- =u= - Unmarks a file
- =U= - Unmarks all files in buffer
- =* t= / =t= - Inverts marked files in buffer
- =% m= - Mark files in buffer using regular expression
- =*= - Lots of other auto-marking functions
- =k= / =K= - "Kill" marked items (refresh buffer with =g= / =g r= to get them back)
- Many operations can be done on a single file if there are no active marks!

**** Copying and Renaming files

- =C= - Copy marked files (or if no files are marked, the current file)
- Copying single and multiple files
- =U= - Unmark all files in buffer
- =R= - Rename marked files, renaming multiple is a move!
- =% R= - Rename based on regular expression: =^test= , =old-\&=

**** Power Command:
=C-x C-q= (=dired-toggle-read-only=) - Makes all file names in the buffer
editable directly to rename them!  Press =Z Z= to confirm renaming or =Z Q= to abort.

**** Deleting Files

- =D= - Delete marked file
- =d= - Mark file for deletion
- =x= - Execute deletion for marks
- =delete-by-moving-to-trash= - Move to trash instead of deleting permanently

**** Creating and extracting archives

- =Z= - Compress or uncompress a file or folder to (=.tar.gz=)
- =c= - Compress selection to a specific file
- =dired-compress-files-alist= - Bind compression commands to file extension

**** Other common operations

- =T= - Touch (change timestamp)
- =M= - Change file mode
- =O= - Change file owner
- =G= - Change file group
- =S= - Create a symbolic link to this file
- =L= - Load an Emacs Lisp file into Emacs


*** Configuration

#+begin_src emacs-lisp

  (use-package dired
	:ensure nil
	:commands (dired dired-jump)
	:bind (("C-x C-j" . dired-jump))
	:custom ((setq insert-directory-program "gls" dired-use-ls-dired t)
			 (setq dired-listing-switches "-al --group-directories-first"))
	:config
	(evil-collection-define-key 'normal 'dired-mode-map
	  "h" 'dired-single-up-directory
	  "l" 'dired-single-buffer))

  (use-package dired-single)

  (use-package all-the-icons-dired
	:hook (dired-mode . all-the-icons-dired-mode))

  (use-package dired-open
	:config
	;; Doesn't work as expected!
	;;(add-to-list 'dired-open-functions #'dired-open-xdg t)
	(setq dired-open-extensions '(("png" . "feh")
								  ("mkv" . "mpv"))))

  (use-package dired-hide-dotfiles
	:hook (dired-mode . dired-hide-dotfiles-mode)
	:config
	(evil-collection-define-key 'normal 'dired-mode-map
	  "H" 'dired-hide-dotfiles-mode))

#+end_src

** NeoTree
*** KeyBindings

 - =n= next line, =p= previous line。
 - =SPC= or =RET= or =TAB= Open current item if it is a file. Fold/Unfold current item if it is a directory.
 - =U= Go up a directory
 - =g= Refresh
 - =A= Maximize/Minimize the NeoTree Window
 - =H= Toggle display hidden files
 - =O= Recursively open a directory
 - =C-c C-n= Create a file or create a directory if filename ends with a ‘/’
 - =C-c C-d= Delete a file or a directory.
 - =C-c C-r= Rename a file or a directory.
 - =C-c C-c= Change the root directory.
 - =C-c C-p= Copy a file or a directory.


*** Configuration

#+begin_src emacs-lisp

  (use-package neotree
	:config
	(setq neo-theme (if (display-graphic-p) 'icons 'arrow)))


#+end_src

* Structure Templates
#+begin_src emacs-lisp
  (with-eval-after-load 'org
	  (require 'org-tempo)
	(add-to-list 'org-structure-template-alist '("sh" . "src shell"))
	(add-to-list 'org-structure-template-alist '("py" . "src python"))
	(add-to-list 'org-structure-template-alist '("el" . "src emacs-lisp"))
	(add-to-list 'org-structure-template-alist '("rb" . "src ruby"))
	(add-to-list 'org-structure-template-alist '("js" . "src javascript")))

#+end_src

#+RESULTS:
: ((el . src emacs-lisp) (py . src python) (sh . src shell) (a . export ascii) (c . center) (C . comment) (e . example) (E . export) (h . export html) (l . export latex) (q . quote) (s . src) (v . verse))
* Applications
** example config 'Some App'
#+begin_src conf-unix :tangle ~/.config/some-app/config :mkdirp yes

	value=4

#+end_src

